routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\API\ProfileController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\LevelFourCategoryController;
use App\Http\Controllers\LevelThreeCategoryController;
use App\Http\Controllers\LevelTwoCategoryController;
use App\Http\Controllers\MainCategoryController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UploadController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/dashboard');
});
//homepage
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
//
Route::get('/test', [ProfileController::class, 'get_level_two'])->name('payment');
//
Route::get('/demo', [PaymentsController::class, 'payment'])->name('demo');
Route::get('/jambopay', function () {
    return view('welcome');
});
Route::get('/payment', function () {
    return view('admin.users.payment');
})->middleware(['auth'])->name('payment');

//Route::post('/user-payment', [PesaPalController::class, 'pesapalIframe'])->name('user-payment');

//Route::post('/dashboard', [HomeController::class, 'index'])->name('dashboard.post');
Route::get('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.disbursed_payments_filter');
Route::post('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.post');

//buyers
Route::resource('app-users', UserController::class);
Route::get('weekly-sales',  [UserController::class, 'weekly'])->name('weekly-sales');
Route::get('books-bought',  [UserController::class, 'bought'])->name('books-bought');

//Route::get('/test', [TransactionController::class, 'payment'])->name('test');

//admin status
Route::post('update-status-admin/{id}', [AdminController::class,'statusUpdate'])->name('status.update');
//jambopay

//app-admins
Route::resource('app-admins', AdminController::class);
Route::resource('languages', LanguageController::class);
Route::resource('publishers', PublisherController::class);
Route::post('delete-admin/{id?}', [AdminController::class,'delete']);

//books
Route::resource('catalogue-books', BookController::class);
Route::get('book/delete/{id}', [BookController::class, 'deleteBook'])->name('book.delete');

//authors
Route::resource('catalogue-authors', AuthorController::class);
Route::resource('main-categories', MainCategoryController::class);
Route::resource('level-two-categories', LevelTwoCategoryController::class);
Route::resource('level-three-categories', LevelThreeCategoryController::class);
Route::resource('level-four-categories', LevelFourCategoryController::class);
Route::resource('upload', UploadController::class);
Route::post('files/upload/large', [UploadController::class, 'uploadLargeFiles'])->name('files.upload.large');

//authors

//user-management
Route::get('catalogue', [HomeController::class, 'viewProviders'])->name('catalogue.index');
Route::get('catalogue/edit', [HomeController::class, 'viewProviders'])->name('catalogue.edit');
Route::get('catalogue/show', [HomeController::class, 'viewProviders'])->name('catalogue.show');
Route::get('catalogue/delete/{id}', [HomeController::class, 'deletePost'])->name('catalogue.delete');



Route::get('languages/delete/{id}', [HomeController::class, 'deletelanguages'])->name('languages.delete');
Route::get('publishers/delete/{id}', [HomeController::class, 'deletepublishers'])->name('publishers.delete');
Route::get('publishe/delete/{id}', [HomeController::class, 'deleteAuthors'])->name('authors.delete');

//profile update
Route::resource('profile', ProfileController::class);
//transaction
Route::resource('mpesa', TransactionController::class);
Route::get('mpesa-failed', [TransactionController::class, 'failedMpesaTransactions'])->name('mpesa.transactions.failed');
Route::get('jambopay', [TransactionController::class, 'pesapal'])->name('jambopay');

Route::get('approve-transaction/{reference_number}', [TransactionController::class, 'approve'])->name('approve.transaction');

//default list
Route::get('/default', [UserController::class, 'default'])->name('default');

//Route::get('get-mpesa-transactions', [MpesaTransactionController::class, 'get_mpesa_transactions'])->name('get-mpesa-transactions');
//here
Route::get('services/two-datatables', 'AdminController@getUsersDataTables');
Route::get('services/two-datatables/posts','AdminController@getPostsDataTables');
//mpesa dummy
Route::get('mpesa-data', [AdminController::class, 'mpesaData'])->name('mpesa.data');
Route::get('mpesa-data-failed', [AdminController::class, 'mpesaDataFailed'])->name('mpesa.data.failed');
Route::get('pesapal-data', [AdminController::class, 'PalData'])->name('pesapal.data');

Route::get('/getSubCounty/{id}', [AdminController::class, 'getSubCounty'])->name('getSubCounty');
Route::get('/getSubThree/{id}', [AdminController::class, 'getSubThree'])->name('getSubThree');
Route::get('/getSubFour/{id}', [AdminController::class, 'getSubFour'])->name('getSubFour');
Route::post('add-main-category', [BookController::class, 'mainCategoty'])->name('add-main-category');
Route::post('add-main-category-two', [BookController::class, 'mainCategotyTwo'])->name('add-main-category-two');
Route::post('add-main-category-three', [BookController::class, 'mainCategotyThree'])->name('add-main-category-three');
Route::post('add-language', [LanguageController::class, 'mainLanguage'])->name('add-language');
Route::post('add-publisher', [PublisherController::class, 'mainPublisher'])->name('add-publisher');
Route::get('/get_user_level_two_books',[ProfileController::class, 'levelTwoBooks']);
Route::get('/get-transaction', [AdminController::class, 'getTransaction'])->name('ajaxdata.fetchtransaction');
Route::post('update-transaction', [AdminController::class, 'updateTransaction'])->name('ajaxdata.updatetransaction');

//edit main category
//edit
Route::post('ajaxdata/postdata', [HomeController::class, 'postdata'])->name('ajaxdata.postdata');
Route::post('ajaxdata/postdatatwo', [HomeController::class, 'postdatatwo'])->name('ajaxdata.postdatatwo');
Route::post('ajaxdata/postdatathree', [HomeController::class, 'postdatathree'])->name('ajaxdata.postdatathree');
Route::post('ajaxdata/postdatafour', [HomeController::class, 'postdatafour'])->name('ajaxdata.postdatafour');

Route::get('ajaxdata/fetchdatas', [LanguageController::class, 'fetchdatas'])->name('ajaxdata.fetchdatas');
Route::get('ajaxdata/main', [MainCategoryController::class, 'fetchdata'])->name('ajaxdata.main');
Route::get('ajaxdata/two', [LevelTwoCategoryController::class, 'fetchdata'])->name('ajaxdata.two');
Route::get('ajaxdata/three', [LevelThreeCategoryController::class, 'fetchdata'])->name('ajaxdata.three');
Route::get('ajaxdata/four', [LevelFourCategoryController::class, 'fetchdata'])->name('ajaxdata.four');


Route::post('ajaxdata/postdatas', [LanguageController::class, 'postLanguage'])->name('ajaxdata.postdatas');

Route::get('ajaxdata/fetchdatass', [PublisherController::class, 'fetchdatass'])->name('ajaxdata.fetchdatass');
Route::post('ajaxdata/postdatass', [PublisherController::class, 'postLanguages'])->name('ajaxdata.postdatass');
Route::post('destroy/{id}', [PublisherController::class, 'destroys']);
//
//Route::get('ajaxdata/fetchdatasss', [PublisherController::class, 'fetchdatasss'])->name('ajaxdata.fetchdatasss');
//Route::post('ajaxdata/postdatasss', [PublisherController::class, 'postLanguagess'])->name('ajaxdata.postdatasss');
//Route::post('destroy/{id}', [PublisherController::class, 'destroys']);


Route::get('ajaxdata/fetchdat', [AuthorController::class, 'fetchdat'])->name('ajaxdata.fetchda');
Route::post('ajaxdata/postdat', [AuthorController::class, 'postLanguag'])->name('ajaxdata.postda');
Route::get('delete-author/{id}', [AuthorController::class, 'delete'])->name('catalogue-authors.delete');

Route::post('destroy/{id}', [HomeController::class, 'destroy']);

//datatable routes
Route::prefix('datatables')->group(function () {
    Route::get('get-app-users', [UserController::class, 'getUsers'])->name('get-app-users');
    Route::get('get-admin-users', [AdminController::class, 'getAdminUsers'])->name('get-admin-users');
    Route::get('get-app-authors', [AuthorController::class, 'getAuthors'])->name('get-app-authors');
    Route::get('get-app-books', [BookController::class, 'getBooks'])->name('get-app-books');
    Route::get('get-app-languages', [LanguageController::class, 'getLanguages'])->name('get-app-languages');
    Route::get('get-app-publishers', [PublisherController::class, 'getpublishers'])->name('get-app-publishers');
    Route::get('get-most-bought-books', [BookController::class, 'getMostBoughtBooks'])->name('get-most-bought-books');


    Route::get('get-app-admins', [AdminController::class, 'getAdmins'])->name('get-app-admins');
//    Route::get('get-app-transactions', [TransactionController::class, 'getTransactions'])->name('get-app-admins');

    Route::get('get-catalogue', [HomeController::class, 'getCategory'])->name('get-catalogue');
    Route::get('get-catalogue-two', [HomeController::class, 'getCategoryTwo'])->name('get-catalogue-two');

routes/web.php
<?php

use App\Http\Controllers\API\ApiMpesaController;
use App\Http\Controllers\BookPaymentController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\PesaPalController;
use App\Http\Controllers\TransactionController;
use App\Models\Book;
use App\Models\BookPayment;
use App\Models\Jambopay;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('moran', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
});

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
//    return view('welcome');
});
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/callbacks', [PesaPalController::class, 'callbacks'])->name('callbacks');
Route::post('/mpesa/callback', [ApiMpesaController::class, 'callback'])->name('callback');

require __DIR__.'/auth.php';

Route::get('/redirect', [PaymentsController::class, 'paymentsuccess'])->name('redirect');
Route::get('/redirects', [\App\Http\Controllers\CallbackController::class, 'redirect'])->name('redirects');

Route::get('/listenipn', [PaymentsController::class, 'paymentconfirmation'])->name('listenipn');
Route::get('/jambopay/{user_id}/{amount}/{book_id}/{name}', function () {
    return view('welcome');
});
Route::post('pay', [JambopayController::class,'jambopay']);

Route::post('/checkout', [JambopayController::class,'checkout'])->name('checkout');
Route::post('/successful-transaction', [JambopayController::class, 'showSuccessfulTransaction']);
Route::post('/cancel-transaction', [JambopayController::class, 'cancelTransaction']);

resources/views/admin/custom/profile.blade.php
@extends('admin.layout.master')
@section('content')
        <!--begin::Profile Personal Information-->
        <div class="d-flex flex-row">
            <!--begin::Aside-->
            <!--end::Aside-->
            <!--begin::Content-->
            <div class="flex-row-fluid ml-lg-8">
                <!--begin::Card-->
                <div class="card card-custom card-stretch">
                    <!--begin::Header-->
                    <div class="card-header py-3">
                        <div class="card-title align-items-start flex-column">
                            <h3 class="card-label font-weight-bolder text-dark">Admin Information</h3>
                            <span class="text-muted font-weight-bold font-size-sm mt-1">Update your personal informaiton</span>
                        </div>
                    </div>
                    <!--end::Header-->
                    <!--begin::Form-->
                    <form class="form" action="{{route('admin.profile.store')}}" method="POST" enctype="multipart/form-data" >
                        <!--begin::Body-->
                        {{csrf_field()}}
                        <div class="card-body">
                            <div class="row">
                                <label class="col-xl-3"></label>
                                <div class="col-lg-9 col-xl-6">
                                    <h5 class="font-weight-bold mb-6">Admin Info</h5>
                                </div>
                            </div>
                            <input type="hidden" name="id" value="{{ $user->id}}">

                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Avatar</label>
                                <div class="col-lg-9 col-xl-6">
                                    <div class="image-input image-input-outline" id="kt_profile_avatar" style="background-image: url({{asset('assets/media/svg/avatars/015-boy-6.svg')}})">
                                        <div class="image-input-wrapper" style="background-image: url({{asset('assets/media/svg/avatars/015-boy-6.svg')}})"></div>
                                        <label class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="change" data-toggle="tooltip" title="" data-original-title="Change avatar">
                                            <i class="fa fa-pen icon-sm text-muted"></i>
                                            <input type="file" name="profile_avatar" accept=".png, .jpg, .jpeg" />
                                            <input type="hidden" name="profile_avatar_remove" />
                                        </label>
                                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="cancel" data-toggle="tooltip" title="Cancel avatar">
																	<i class="ki ki-bold-close icon-xs text-muted"></i>
																</span>
                                        <span class="btn btn-xs btn-icon btn-circle btn-white btn-hover-text-primary btn-shadow" data-action="remove" data-toggle="tooltip" title="Remove avatar">
																	<i class="ki ki-bold-close icon-xs text-muted"></i>
																</span>
                                    </div>
                                    <span class="form-text text-muted">Allowed file types: png, jpg, jpeg.</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Name</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control form-control-lg form-control-solid" value="{{ $user->name }}"  name="name" type="text" required placeholder="Full Name"/>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Username</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control form-control-lg form-control-solid" value="{{ $user->username }}" name="username" type="text" required placeholder="Username" />
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-xl-3"></label>
                                <div class="col-lg-9 col-xl-6">
                                    <h5 class="font-weight-bold mt-10 mb-6">Contact Info</h5>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Phone Number</label>
                                <div class="col-lg-9 col-xl-6">
                                    <div class="input-group input-group-lg input-group-solid">
                                        <div class="input-group-prepend">
																	<span class="input-group-text">
																		<i class="la la-phone"></i>
																	</span>
                                        </div>
                                        <input type="text" class="form-control form-control-lg form-control-solid" value="{{ $user->phone_number }}"  name="phone_number" placeholder="Phone" required />
                                    </div>
                                    <span class="form-text text-muted">We'll never share your email with anyone else.</span>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Email Address</label>
                                <div class="col-lg-9 col-xl-6">
                                    <div class="input-group input-group-lg input-group-solid">
                                        <div class="input-group-prepend">
											<span class="input-group-text">
												<i class="la la-at"></i>
											</span>
                                        </div>
                                        <input type="text" class="form-control form-control-lg form-control-solid" value="{{ $user->email }}" name="email" required placeholder="Email" />
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <label class="col-3"></label>
                                <div class="col-9">
                                    <h6 class="text-dark font-weight-bold mb-10">Change Or Recover Your Password:</h6>
                                </div>
                            </div>
                            <!--end::Row-->
{{--                            <!--begin::Group-->--}}
{{--                            <div class="form-group row">--}}
{{--                                <label class="col-xl-3 col-lg-3 col-form-label">Current Password</label>--}}
{{--                                <div class="col-lg-9 col-xl-6">--}}
{{--                                    <input class="form-control form-control-lg form-control-solid mb-1" name="current" type="password" />--}}
{{--                                    <a href="#" class="font-weight-bold font-size-sm">Forgot password ?</a>--}}
{{--                                </div>--}}
{{--                            </div>--}}
{{--                            <!--end::Group-->--}}
                            <!--begin::Group-->
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">New Password</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control form-control-lg form-control-solid" type="password" name="password"
                                           required />
                                </div>
                            </div>
                            <!--end::Group-->
                            <!--begin::Group-->
                            <div class="form-group row">
                                <label class="col-xl-3 col-lg-3 col-form-label">Verify Password</label>
                                <div class="col-lg-9 col-xl-6">
                                    <input class="form-control form-control-lg form-control-solid" type="password"
                                           name="password_confirmation" />
                                </div>
                            </div>
                            <div class="card-toolbar">
                                <button type="submit" class="btn btn-success mr-2">Save Changes</button>
                                <a href="{{route('dashboard')}}" class="btn btn-success font-weight-bolder border-top px-9 py-4">Cancel</a>

                            </div>
                        </div>
                        <!--end::Body-->
                    </form>
                    <!--end::Form-->
                </div>
            </div>
            <!--end::Content-->
        </div>
        <!--end::Profile Personal Information-->
    @endsection