routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\API\ProfileController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\LevelFourCategoryController;
use App\Http\Controllers\LevelThreeCategoryController;
use App\Http\Controllers\LevelTwoCategoryController;
use App\Http\Controllers\MainCategoryController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UploadController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/dashboard');
});
//homepage
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
//
Route::get('/test', [ProfileController::class, 'get_level_two'])->name('payment');
//
Route::get('/demo', [PaymentsController::class, 'payment'])->name('demo');
Route::get('/jambopay', function () {
    return view('welcome');
});
Route::get('/payment', function () {
    return view('admin.users.payment');
})->middleware(['auth'])->name('payment');

//Route::post('/user-payment', [PesaPalController::class, 'pesapalIframe'])->name('user-payment');

//Route::post('/dashboard', [HomeController::class, 'index'])->name('dashboard.post');
Route::get('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.disbursed_payments_filter');
Route::post('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.post');

//buyers
Route::resource('app-users', UserController::class);
Route::get('weekly-sales',  [UserController::class, 'weekly'])->name('weekly-sales');
Route::get('books-bought',  [UserController::class, 'bought'])->name('books-bought');

//Route::get('/test', [TransactionController::class, 'payment'])->name('test');

//admin status
Route::post('update-status-admin/{id}', [AdminController::class,'statusUpdate'])->name('status.update');
//jambopay

//app-admins
Route::resource('app-admins', AdminController::class);
Route::resource('languages', LanguageController::class);
Route::resource('publishers', PublisherController::class);
Route::post('delete-admin/{id?}', [AdminController::class,'delete']);

//books
Route::resource('catalogue-books', BookController::class);
Route::get('book/delete/{id}', [BookController::class, 'deleteBook'])->name('book.delete');

//authors
Route::resource('catalogue-authors', AuthorController::class);
Route::resource('main-categories', MainCategoryController::class);
Route::resource('level-two-categories', LevelTwoCategoryController::class);
Route::resource('level-three-categories', LevelThreeCategoryController::class);
Route::resource('level-four-categories', LevelFourCategoryController::class);
Route::resource('upload', UploadController::class);
Route::post('files/upload/large', [UploadController::class, 'uploadLargeFiles'])->name('files.upload.large');

//authors

//user-management
Route::get('catalogue', [HomeController::class, 'viewProviders'])->name('catalogue.index');
Route::get('catalogue/edit', [HomeController::class, 'viewProviders'])->name('catalogue.edit');
Route::get('catalogue/show', [HomeController::class, 'viewProviders'])->name('catalogue.show');
Route::get('catalogue/delete/{id}', [HomeController::class, 'deletePost'])->name('catalogue.delete');



Route::get('languages/delete/{id}', [HomeController::class, 'deletelanguages'])->name('languages.delete');
Route::get('publishers/delete/{id}', [HomeController::class, 'deletepublishers'])->name('publishers.delete');
Route::get('publishe/delete/{id}', [HomeController::class, 'deleteAuthors'])->name('authors.delete');

//profile update
Route::resource('profile', ProfileController::class);
//transaction
Route::resource('mpesa', TransactionController::class);
Route::get('mpesa-failed', [TransactionController::class, 'failedMpesaTransactions'])->name('mpesa.transactions.failed');
Route::get('jambopay', [TransactionController::class, 'pesapal'])->name('jambopay');

Route::get('approve-transaction/{reference_number}', [TransactionController::class, 'approve'])->name('approve.transaction');

//default list
Route::get('/default', [UserController::class, 'default'])->name('default');

//Route::get('get-mpesa-transactions', [MpesaTransactionController::class, 'get_mpesa_transactions'])->name('get-mpesa-transactions');
//here
Route::get('services/two-datatables', 'AdminController@getUsersDataTables');
Route::get('services/two-datatables/posts','AdminController@getPostsDataTables');
//mpesa dummy
Route::get('mpesa-data', [AdminController::class, 'mpesaData'])->name('mpesa.data');
Route::get('mpesa-data-failed', [AdminController::class, 'mpesaDataFailed'])->name('mpesa.data.failed');
Route::get('pesapal-data', [AdminController::class, 'PalData'])->name('pesapal.data');

Route::get('/getSubCounty/{id}', [AdminController::class, 'getSubCounty'])->name('getSubCounty');
Route::get('/getSubThree/{id}', [AdminController::class, 'getSubThree'])->name('getSubThree');
Route::get('/getSubFour/{id}', [AdminController::class, 'getSubFour'])->name('getSubFour');
Route::post('add-main-category', [BookController::class, 'mainCategoty'])->name('add-main-category');
Route::post('add-main-category-two', [BookController::class, 'mainCategotyTwo'])->name('add-main-category-two');
Route::post('add-main-category-three', [BookController::class, 'mainCategotyThree'])->name('add-main-category-three');
Route::post('add-language', [LanguageController::class, 'mainLanguage'])->name('add-language');
Route::post('add-publisher', [PublisherController::class, 'mainPublisher'])->name('add-publisher');
Route::get('/get_user_level_two_books',[ProfileController::class, 'levelTwoBooks']);
Route::get('/get-transaction', [AdminController::class, 'getTransaction'])->name('ajaxdata.fetchtransaction');
Route::post('update-transaction', [AdminController::class, 'updateTransaction'])->name('ajaxdata.updatetransaction');

//edit main category
//edit
Route::post('ajaxdata/postdata', [HomeController::class, 'postdata'])->name('ajaxdata.postdata');
Route::post('ajaxdata/postdatatwo', [HomeController::class, 'postdatatwo'])->name('ajaxdata.postdatatwo');
Route::post('ajaxdata/postdatathree', [HomeController::class, 'postdatathree'])->name('ajaxdata.postdatathree');
Route::post('ajaxdata/postdatafour', [HomeController::class, 'postdatafour'])->name('ajaxdata.postdatafour');

Route::get('ajaxdata/fetchdatas', [LanguageController::class, 'fetchdatas'])->name('ajaxdata.fetchdatas');
Route::get('ajaxdata/main', [MainCategoryController::class, 'fetchdata'])->name('ajaxdata.main');
Route::get('ajaxdata/two', [LevelTwoCategoryController::class, 'fetchdata'])->name('ajaxdata.two');
Route::get('ajaxdata/three', [LevelThreeCategoryController::class, 'fetchdata'])->name('ajaxdata.three');
Route::get('ajaxdata/four', [LevelFourCategoryController::class, 'fetchdata'])->name('ajaxdata.four');


Route::post('ajaxdata/postdatas', [LanguageController::class, 'postLanguage'])->name('ajaxdata.postdatas');

Route::get('ajaxdata/fetchdatass', [PublisherController::class, 'fetchdatass'])->name('ajaxdata.fetchdatass');
Route::post('ajaxdata/postdatass', [PublisherController::class, 'postLanguages'])->name('ajaxdata.postdatass');
Route::post('destroy/{id}', [PublisherController::class, 'destroys']);
//
//Route::get('ajaxdata/fetchdatasss', [PublisherController::class, 'fetchdatasss'])->name('ajaxdata.fetchdatasss');
//Route::post('ajaxdata/postdatasss', [PublisherController::class, 'postLanguagess'])->name('ajaxdata.postdatasss');
//Route::post('destroy/{id}', [PublisherController::class, 'destroys']);


Route::get('ajaxdata/fetchdat', [AuthorController::class, 'fetchdat'])->name('ajaxdata.fetchda');
Route::post('ajaxdata/postdat', [AuthorController::class, 'postLanguag'])->name('ajaxdata.postda');
Route::get('delete-author/{id}', [AuthorController::class, 'delete'])->name('catalogue-authors.delete');

Route::post('destroy/{id}', [HomeController::class, 'destroy']);

//datatable routes
Route::prefix('datatables')->group(function () {
    Route::get('get-app-users', [UserController::class, 'getUsers'])->name('get-app-users');
    Route::get('get-admin-users', [AdminController::class, 'getAdminUsers'])->name('get-admin-users');
    Route::get('get-app-authors', [AuthorController::class, 'getAuthors'])->name('get-app-authors');
    Route::get('get-app-books', [BookController::class, 'getBooks'])->name('get-app-books');
    Route::get('get-app-languages', [LanguageController::class, 'getLanguages'])->name('get-app-languages');
    Route::get('get-app-publishers', [PublisherController::class, 'getpublishers'])->name('get-app-publishers');
    Route::get('get-most-bought-books', [BookController::class, 'getMostBoughtBooks'])->name('get-most-bought-books');


    Route::get('get-app-admins', [AdminController::class, 'getAdmins'])->name('get-app-admins');
//    Route::get('get-app-transactions', [TransactionController::class, 'getTransactions'])->name('get-app-admins');

    Route::get('get-catalogue', [HomeController::class, 'getCategory'])->name('get-catalogue');
    Route::get('get-catalogue-two', [HomeController::class, 'getCategoryTwo'])->name('get-catalogue-two');

routes/web.php
<?php

use App\Http\Controllers\API\ApiMpesaController;
use App\Http\Controllers\BookPaymentController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\PesaPalController;
use App\Http\Controllers\TransactionController;
use App\Models\Book;
use App\Models\BookPayment;
use App\Models\Jambopay;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('moran', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
});

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
//    return view('welcome');
});
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/callbacks', [PesaPalController::class, 'callbacks'])->name('callbacks');
Route::post('/mpesa/callback', [ApiMpesaController::class, 'callback'])->name('callback');

require __DIR__.'/auth.php';

Route::get('/redirect', [PaymentsController::class, 'paymentsuccess'])->name('redirect');
Route::get('/redirects', [\App\Http\Controllers\CallbackController::class, 'redirect'])->name('redirects');

Route::get('/listenipn', [PaymentsController::class, 'paymentconfirmation'])->name('listenipn');
Route::get('/jambopay/{user_id}/{amount}/{book_id}/{name}', function () {
    return view('welcome');
});
Route::post('pay', [JambopayController::class,'jambopay']);

Route::post('/checkout', [JambopayController::class,'checkout'])->name('checkout');
Route::post('/successful-transaction', [JambopayController::class, 'showSuccessfulTransaction']);
Route::post('/cancel-transaction', [JambopayController::class, 'cancelTransaction']);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;
    use \Conner\Tagging\Taggable;

    protected $fillable = [
        'isbn',
        'file_type',
        'title',
        'description',
        'published',
        'embargo_date',
        'category_id',
        'level_two_category_id',
        'level_three_category_id',
        'level_four_category_id',
        'tags',
        'author_id',
        'authors',
        'edition',
        'publication_date',
        'copyright',
        'image',
        'url',
        'language',
        'publisher',
        'price',
        'created_at',
        'updated_at',
        'book_tags',

    ];

    public function authors()
    {
        return $this->belongsTo('App\Author');
    }
    public function book_payments()
    {
        return $this->hasMany(BookPayment::class);
    }
    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }
    /**
     * Set the categories
     *
     */
    public function setCatAttribute($value)
    {
        $this->attributes['authors'] = json_encode($value);
    }
    public function getCatAttribute($value)
    {
        return $this->attributes['authors'] = json_decode($value);
    }
    public function setTagsAttribute($value)
    {
        $this->attributes['book_tags'] = json_encode($value);
    }
    public function getTagsAttribute($value)
    {
        return $this->attributes['book_tags'] = json_decode($value);
    }
    public function books()
    {
        return $this->hasMany(Book::class);
    }
}

resources/views/admin/books/index-old.blade.php
@extends('admin.layout.master')
@section('content')
    <div class="card card-custom" style="margin-top: -5%;">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Registered Moran Publishers Books
                </h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('admin.catalogue-books.create') }}" type="button" class="btn btn-primary font-weight-bolder">
                    <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24" />
                                <circle fill="#000000" cx="9" cy="15" r="6" />
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                            </g>
                        </svg>
                        <!--end::Svg Icon-->
                    </span>Register New Book
                </a>
                <!--end::Button-->
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="example">
                                <thead style="font-weight: bold">
                                <tr>
                                    <th>No</th>
                                    <th>Image</th>
                                    <th>EAN</th>
                                    <th>Title</th>
                                    <th>Edition</th>
                                    <th>Publication Date</th>
                                    <th>Copyright</th>
                                    <th>Tag</th>
                                    <th>Language</th>
                                    <th>Price</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Image</th>
                                    <th>EAN</th>
                                    <th>Title</th>
                                    <th>Edition</th>
                                    <th>Publication Date</th>
                                    <th>Copyright</th>
                                    <th>Tag</th>
                                    <th>Language</th>
                                    <th>Price</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(document).ready(function() {
            // Setup - add a text input to each footer cell
            $('#example thead tr').clone(true).appendTo( '#example thead' );
            $('#example thead tr:eq(1) th').each( function (i) {
                var title = $(this).text();
                $(this).html( '<input type="text" placeholder="Search '+title+'" />' );

                $( 'input', this ).on( 'keyup change', function () {
                    if ( table.column(i).search() !== this.value ) {
                        table
                            .column(i)
                            .search( this.value )
                            .draw();
                    }
                } );
            } );

            var table = $('#example').DataTable( {
                orderCellsTop: true,
                fixedHeader: true,
                ajax: APP_URL +'/admin/datatables/get-app-books',
                dom: 'Bfrtip',
                buttons: [
                    'colvis','copy', 'excel', 'print',

                    {
                        extend: 'csvHtml5',
                        text: 'CSV',
                        exportOptions: {
                            columns: [0,1, 2,3,4, 5,6],
                        },
                        footer: true,
                    },
                    'pageLength'
                ],
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable: false, orderable: false},
                    {
                        data: 'image',
                        name: 'image',
                        render: function(data, type, full, meta){
                            return "<img src={{ \Illuminate\Support\Facades\URL::to('/') }}/images/" + data + " width='70' class='img-thumbnail' />";
                        },
                        orderable: false
                    },
                    {data: 'isbn', name: 'isbn'},
                    {data: 'title', name: 'title'},
                    {data: 'edition', name: 'edition'},
                    {data: 'publication_date', name: 'publication_date'},
                    {data: 'copyright', name: 'copyright'},
                    {data: 'tags', name: 'tags',
                        render: function(data, type, full, meta){
                            let color = 'green';
                            return '<span style="color:' + color + '">' + data + '</span>';

                        },
                        orderable: false
                    },
                    {data: 'language', name: 'language'},
                    {data: 'price', name: 'price'},
                    {data: 'action', name: 'action'},

                ],

            } );
        } );
    </script>
@endsection

resources/views/admin/books/index.blade.php
@extends('admin.layout.master')
@section('styles')
    <style>

    </style>
@endsection
@section('content')
    <div class="card card-custom" style="margin-top: -5%;">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Registered Moran Publishers Books
                </h3>
            </div>
            <div class="card-toolbar">
                <!--begin::Button-->
                <a href="{{ route('admin.catalogue-books.create') }}" type="button" class="btn btn-primary font-weight-bolder">
                    <span class="svg-icon svg-icon-md">
                        <!--begin::Svg Icon | path:assets/media/svg/icons/Design/Flatten.svg-->
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                <rect x="0" y="0" width="24" height="24" />
                                <circle fill="#000000" cx="9" cy="15" r="6" />
                                <path d="M8.8012943,7.00241953 C9.83837775,5.20768121 11.7781543,4 14,4 C17.3137085,4 20,6.6862915 20,10 C20,12.2218457 18.7923188,14.1616223 16.9975805,15.1987057 C16.9991904,15.1326658 17,15.0664274 17,15 C17,10.581722 13.418278,7 9,7 C8.93357256,7 8.86733422,7.00080962 8.8012943,7.00241953 Z" fill="#000000" opacity="0.3" />
                            </g>
                        </svg>
                        <!--end::Svg Icon-->
                    </span>Register New Book
                </a>
                <!--end::Button-->
            </div>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-head-custom table-vertical-center" id="example">
                                <thead style="font-weight: bold">
                                <tr>
                                    <th>No</th>
                                    <th>Image</th>
                                    <th>EAN</th>
                                    <th>Title</th>
                                    <th>Edition</th>
                                    <th>Publication Date</th>
                                    <th>Copyright</th>
                                    {{--<th>Tag</th>--}}
                                    <th>Language</th>
                                    <th>Price</th>
                                    <th>Pages</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Image</th>
                                    <th>EAN</th>
                                    <th>Title</th>
                                    <th>Edition</th>
                                    <th>Publication Date</th>
                                    <th>Copyright</th>
                                    {{--<th>Tag</th>--}}
                                    <th>Language</th>
                                    <th>Price</th>
                                    <th>Pages</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
           $('#example').DataTable({
                orderCellsTop: true,
                fixedHeader: true,
                ajax: APP_URL +'/admin/datatables/get-app-books',
                dom: 'Bfrtip',
                buttons: [
                    'colvis','copy', 'excel', 'print',

                    {
                        extend: 'csvHtml5',
                        text: 'CSV',
                        exportOptions: {
                            columns: [0,1, 2,3,4, 5,6],
                        },
                        footer: true,
                    },
                    'pageLength'
                ],
                columns: [
                    {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable: false, orderable: false},
                    // {data: 'image', name: 'image'},
                    {
                        data: 'image',
                        name: 'image',
                        render: function(data, type, full, meta){
                            return "<img src={{ \Illuminate\Support\Facades\URL::to('/') }}/images/" + data + " width='90' />";
                        },
                        orderable: false
                    },
                    {data: 'isbn', name: 'isbn'},
                    {data: 'title', name: 'title'},
                    {data: 'edition', name: 'edition'},
                    {data: 'publication_date', name: 'publication_date'},
                    {data: 'copyright', name: 'copyright'},
                    {data: 'language', name: 'language'},
                    {data: 'price', name: 'price'},
                    {data: 'pages', name: 'pages'},
                    {data: 'action', name: 'action'},
                ],
            });
    </script>
@endsection