routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AuthorController;
use App\Http\Controllers\Admin\BookController;
use App\Http\Controllers\API\ProfileController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\LevelFourCategoryController;
use App\Http\Controllers\LevelThreeCategoryController;
use App\Http\Controllers\LevelTwoCategoryController;
use App\Http\Controllers\MainCategoryController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\LanguageController;
use App\Http\Controllers\PublisherController;
use App\Http\Controllers\UploadController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\LogsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/dashboard');
});
//homepage
Route::get('/dashboard', [HomeController::class, 'index'])->name('dashboard');
//
Route::get('/test', [ProfileController::class, 'get_level_two'])->name('payment');
//
Route::get('/demo', [PaymentsController::class, 'payment'])->name('demo');
Route::get('/jambopay', function () {
    return view('welcome');
});
Route::get('/payment', function () {
    return view('admin.users.payment');
})->middleware(['auth'])->name('payment');

//Route::post('/user-payment', [PesaPalController::class, 'pesapalIframe'])->name('user-payment');

//Route::post('/dashboard', [HomeController::class, 'index'])->name('dashboard.post');
Route::get('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.disbursed_payments_filter');
Route::post('/dashboard/monthly-purchases-filter', [HomeController::class, 'disbursed_payments_filter'])->name('dashboard.post');

//buyers
Route::resource('app-users', UserController::class);
Route::get('weekly-sales',  [UserController::class, 'weekly'])->name('weekly-sales');
Route::get('books-bought',  [UserController::class, 'bought'])->name('books-bought');

//Route::get('/test', [TransactionController::class, 'payment'])->name('test');

//admin status
Route::post('update-status-admin/{id}', [AdminController::class,'statusUpdate'])->name('status.update');
//jambopay

//app-admins
Route::resource('app-admins', AdminController::class);
Route::resource('languages', LanguageController::class);
Route::resource('publishers', PublisherController::class);
Route::post('delete-admin/{id?}', [AdminController::class,'delete']);

//books
Route::resource('catalogue-books', BookController::class);
Route::get('book/delete/{id}', [BookController::class, 'deleteBook'])->name('book.delete');

//authors
Route::resource('catalogue-authors', AuthorController::class);
Route::resource('main-categories', MainCategoryController::class);
Route::resource('level-two-categories', LevelTwoCategoryController::class);
Route::resource('level-three-categories', LevelThreeCategoryController::class);
Route::resource('level-four-categories', LevelFourCategoryController::class);
Route::resource('upload', UploadController::class);
Route::post('files/upload/large', [UploadController::class, 'uploadLargeFiles'])->name('files.upload.large');

//authors

//user-management
Route::get('catalogue', [HomeController::class, 'viewProviders'])->name('catalogue.index');
Route::get('catalogue/edit', [HomeController::class, 'viewProviders'])->name('catalogue.edit');
Route::get('catalogue/show', [HomeController::class, 'viewProviders'])->name('catalogue.show');
Route::get('catalogue/delete/{id}', [HomeController::class, 'deletePost'])->name('catalogue.delete');



Route::get('languages/delete/{id}', [HomeController::class, 'deletelanguages'])->name('languages.delete');
Route::get('publishers/delete/{id}', [HomeController::class, 'deletepublishers'])->name('publishers.delete');
Route::get('publishe/delete/{id}', [HomeController::class, 'deleteAuthors'])->name('authors.delete');

//profile update
Route::resource('profile', ProfileController::class);
//transaction
Route::resource('mpesa', TransactionController::class);
Route::get('mpesa-failed', [TransactionController::class, 'failedMpesaTransactions'])->name('mpesa.transactions.failed');
Route::get('jambopay', [TransactionController::class, 'pesapal'])->name('jambopay');

Route::get('approve-transaction/{reference_number}', [TransactionController::class, 'approve'])->name('approve.transaction');

//default list
Route::get('/default', [UserController::class, 'default'])->name('default');

//Route::get('get-mpesa-transactions', [MpesaTransactionController::class, 'get_mpesa_transactions'])->name('get-mpesa-transactions');
//here
Route::get('services/two-datatables', 'AdminController@getUsersDataTables');
Route::get('services/two-datatables/posts','AdminController@getPostsDataTables');
//mpesa dummy
Route::get('mpesa-data', [AdminController::class, 'mpesaData'])->name('mpesa.data');
Route::get('mpesa-data-failed', [AdminController::class, 'mpesaDataFailed'])->name('mpesa.data.failed');
Route::get('pesapal-data', [AdminController::class, 'PalData'])->name('pesapal.data');

Route::get('/getSubCounty/{id}', [AdminController::class, 'getSubCounty'])->name('getSubCounty');
Route::get('/getSubThree/{id}', [AdminController::class, 'getSubThree'])->name('getSubThree');
Route::get('/getSubFour/{id}', [AdminController::class, 'getSubFour'])->name('getSubFour');
Route::post('add-main-category', [BookController::class, 'mainCategoty'])->name('add-main-category');
Route::post('add-main-category-two', [BookController::class, 'mainCategotyTwo'])->name('add-main-category-two');
Route::post('add-main-category-three', [BookController::class, 'mainCategotyThree'])->name('add-main-category-three');
Route::post('add-language', [LanguageController::class, 'mainLanguage'])->name('add-language');
Route::post('add-publisher', [PublisherController::class, 'mainPublisher'])->name('add-publisher');
Route::get('/get_user_level_two_books',[ProfileController::class, 'levelTwoBooks']);
Route::get('/get-transaction', [AdminController::class, 'getTransaction'])->name('ajaxdata.fetchtransaction');
Route::post('update-transaction', [AdminController::class, 'updateTransaction'])->name('ajaxdata.updatetransaction');

//edit main category
//edit
Route::post('ajaxdata/postdata', [HomeController::class, 'postdata'])->name('ajaxdata.postdata');
Route::post('ajaxdata/postdatatwo', [HomeController::class, 'postdatatwo'])->name('ajaxdata.postdatatwo');
Route::post('ajaxdata/postdatathree', [HomeController::class, 'postdatathree'])->name('ajaxdata.postdatathree');
Route::post('ajaxdata/postdatafour', [HomeController::class, 'postdatafour'])->name('ajaxdata.postdatafour');

Route::get('ajaxdata/fetchdatas', [LanguageController::class, 'fetchdatas'])->name('ajaxdata.fetchdatas');
Route::get('ajaxdata/main', [MainCategoryController::class, 'fetchdata'])->name('ajaxdata.main');
Route::get('ajaxdata/two', [LevelTwoCategoryController::class, 'fetchdata'])->name('ajaxdata.two');
Route::get('ajaxdata/three', [LevelThreeCategoryController::class, 'fetchdata'])->name('ajaxdata.three');
Route::get('ajaxdata/four', [LevelFourCategoryController::class, 'fetchdata'])->name('ajaxdata.four');


Route::post('ajaxdata/postdatas', [LanguageController::class, 'postLanguage'])->name('ajaxdata.postdatas');

Route::get('ajaxdata/fetchdatass', [PublisherController::class, 'fetchdatass'])->name('ajaxdata.fetchdatass');
Route::post('ajaxdata/postdatass', [PublisherController::class, 'postLanguages'])->name('ajaxdata.postdatass');
Route::post('destroy/{id}', [PublisherController::class, 'destroys']);
//
//Route::get('ajaxdata/fetchdatasss', [PublisherController::class, 'fetchdatasss'])->name('ajaxdata.fetchdatasss');
//Route::post('ajaxdata/postdatasss', [PublisherController::class, 'postLanguagess'])->name('ajaxdata.postdatasss');
//Route::post('destroy/{id}', [PublisherController::class, 'destroys']);


Route::get('ajaxdata/fetchdat', [AuthorController::class, 'fetchdat'])->name('ajaxdata.fetchda');
Route::post('ajaxdata/postdat', [AuthorController::class, 'postLanguag'])->name('ajaxdata.postda');
Route::get('delete-author/{id}', [AuthorController::class, 'delete'])->name('catalogue-authors.delete');

Route::post('destroy/{id}', [HomeController::class, 'destroy']);

//datatable routes
Route::prefix('datatables')->group(function () {
    Route::get('get-app-users', [UserController::class, 'getUsers'])->name('get-app-users');
    Route::get('get-admin-users', [AdminController::class, 'getAdminUsers'])->name('get-admin-users');
    Route::get('get-app-authors', [AuthorController::class, 'getAuthors'])->name('get-app-authors');
    Route::get('get-app-books', [BookController::class, 'getBooks'])->name('get-app-books');
    Route::get('get-app-languages', [LanguageController::class, 'getLanguages'])->name('get-app-languages');
    Route::get('get-app-publishers', [PublisherController::class, 'getpublishers'])->name('get-app-publishers');
    Route::get('get-most-bought-books', [BookController::class, 'getMostBoughtBooks'])->name('get-most-bought-books');


    Route::get('get-app-admins', [AdminController::class, 'getAdmins'])->name('get-app-admins');
//    Route::get('get-app-transactions', [TransactionController::class, 'getTransactions'])->name('get-app-admins');

    Route::get('get-catalogue', [HomeController::class, 'getCategory'])->name('get-catalogue');
    Route::get('get-catalogue-two', [HomeController::class, 'getCategoryTwo'])->name('get-catalogue-two');

routes/web.php
<?php

use App\Http\Controllers\API\ApiMpesaController;
use App\Http\Controllers\BookPaymentController;
use App\Http\Controllers\JambopayController;
use App\Http\Controllers\PaymentsController;
use App\Http\Controllers\PesaPalController;
use App\Http\Controllers\TransactionController;
use App\Models\Book;
use App\Models\BookPayment;
use App\Models\Jambopay;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Storage;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('moran', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
});

Route::get('/', function () {
    return \Illuminate\Support\Facades\Redirect::to('admin/login');
//    return view('welcome');
});
//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth'])->name('dashboard');
Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/home');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/callbacks', [PesaPalController::class, 'callbacks'])->name('callbacks');
Route::post('/mpesa/callback', [ApiMpesaController::class, 'callback'])->name('callback');

require __DIR__.'/auth.php';

Route::get('/redirect', [PaymentsController::class, 'paymentsuccess'])->name('redirect');
Route::get('/redirects', [\App\Http\Controllers\CallbackController::class, 'redirect'])->name('redirects');

Route::get('/listenipn', [PaymentsController::class, 'paymentconfirmation'])->name('listenipn');
Route::get('/jambopay/{user_id}/{amount}/{book_id}/{name}', function () {
    return view('welcome');
});
Route::post('pay', [JambopayController::class,'jambopay']);

Route::post('/checkout', [JambopayController::class,'checkout'])->name('checkout');
Route::post('/successful-transaction', [JambopayController::class, 'showSuccessfulTransaction']);
Route::post('/cancel-transaction', [JambopayController::class, 'cancelTransaction']);

app/Http/Controllers/API/TransactionController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Yajra\DataTables\Facades\DataTables;
use Bryceandy\Laravel_Pesapal\Pesapal\pesapalCheckStatus;
use Bryceandy\Laravel_Pesapal\Models\Transaction;
use Bryceandy\Laravel_Pesapal\Pesapal\OAuthSignatureMethod_HMAC_SHA1;
use Bryceandy\Laravel_Pesapal\Pesapal\OAuthConsumer;
use Bryceandy\Laravel_Pesapal\Pesapal\OAuthRequest;
class TransactionController extends Controller
{
    public function payment(Request $request)
    {
        return response()->json([
            'status' => 'success',
            'message' => $request->all(),

        ]);
        //pesapal params
        $token = $params = NULL;
        $consumer_key 		= env('PESAPAL_KEY');
        $consumer_secret 	= env('PESAPAL_SECRET');

        $signature_method = new OAuthSignatureMethod_HMAC_SHA1();

        if(env('PESAPAL_IS_LIVE') == 'true')
        {
            $iframelink = 'https://www.pesapal.com/api/PostPesapalDirectOrderV4';
        }
        else
        {
            $iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';
        }

        //get form details
        $amount = intval(number_format($request->amount, 0));
        $currency = $request->currency;
        $desc = $request->description;
        $type = 'MERCHANT';
        $ref =  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',5);
        $reference 	=  substr(str_shuffle($ref),0,10);
        $first_name = $request->first_name;
        $last_name = $request->last_name;
        $email = $request->email;
        $phonenumber = $request->phone_number;

        $callback_url = env('PESAPAL_CALLBACK_URL');

        //storing into the database
        Transaction::make($first_name, $last_name, $email, $amount, $currency, $desc, $reference, $phonenumber);

        /*Do not touch this xml variable in any way as it is the source of errors when you try
        to be clever and add extra spaces inside it*/
        $post_xml	= "<?xml version=\"1.0\" encoding=\"utf-8\"?>
				   <PesapalDirectOrderInfo
						xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
					  	xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"
					  	Currency=\"".$currency."\"
					  	Amount=\"".$amount."\"
					  	Description=\"".$desc."\"
					  	Type=\"".$type."\"
					  	Reference=\"".$reference."\"
					  	FirstName=\"".$first_name."\"
					  	LastName=\"".$last_name."\"
					  	Email=\"".$email."\"
					  	PhoneNumber=\"".$phonenumber."\"
					  	xmlns=\"http://www.pesapal.com\" />";
        $post_xml = htmlentities($post_xml);

        $consumer = new OAuthConsumer($consumer_key, $consumer_secret);

        //post transaction to pesapal
        $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
        $iframe_src->set_parameter("oauth_callback", $callback_url);
        $iframe_src->set_parameter("pesapal_request_data", $post_xml);
        $iframe_src->sign_request($signature_method, $consumer, $token);

        return view ('laravel_pesapal::iframe', compact('iframe_src'));
    }

    public function redirect()
    {
        $pesapalMerchantReference	= null;
        $pesapalTrackingId 		    = null;
        $checkStatus 				= new pesapalCheckStatus();

        if(isset($_GET['pesapal_merchant_reference']))
            $pesapalMerchantReference = $_GET['pesapal_merchant_reference'];

        if(isset($_GET['pesapal_transaction_tracking_id']))
            $pesapalTrackingId = $_GET['pesapal_transaction_tracking_id'];

        //obtaining the payment status after a payment
        $status = $checkStatus->checkStatusUsingTrackingIdandMerchantRef($pesapalMerchantReference,$pesapalTrackingId);

        //display the reference and payment status on the callback page
        return view ('laravel_pesapal::callback_example', compact('pesapalMerchantReference', 'status'));
    }
}

resources/views/admin/transaction/callback_example.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <style>
        body{padding: 5%;}
        h1{text-align: center;}
        ul li a{text-decoration: none}
        ul li{list-style-type: disc}
    </style>
    <title>Payment Status</title>
</head>
<body>

    <h1>Status of Payment</h1>

    <ul>
        {{--the status change will happen only if you put your IPN settings on the dashboard--}}
        <li>Your payment status is currently {{$update->status}}</li>
        <li>The merchant reference is {{$update->reference}}</li>
        <li><a href="/listenipn">REFRESH</a> to reveiew your current payment status!</li>
    </ul>

</body>
</html>

resources/views/admin/transaction/failed-mpesa-transactions.blade.php
@extends('admin.layout.master')
@section('styles')
    <style>
        .status-links {
            display: flex;
            margin: 5px 30px;
        }
        .status-links .badge-danger {
            margin-left: 5px;
        }
    </style>
@endsection
@section('content')
    <!--end::Notice-->
    <div class="row" style="margin-top: -6%;">
        <div class="col bg-light-danger px-6 py-8 rounded-xl mr-7 mb-7">
            <span class="svg-icon svg-icon-3x svg-icon-info d-block my-2">
                <!--begin::Svg Icon | path:/metronic/theme/html/demo1/dist/assets/media/svg/icons/Media/Equalizer.svg-->
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <rect x="0" y="0" width="24" height="24"></rect>
                        <rect fill="#000000" opacity="0.3" x="13" y="4" width="3" height="16" rx="1.5"></rect>
                        <rect fill="#000000" x="8" y="9" width="3" height="11" rx="1.5"></rect>
                        <rect fill="#000000" x="18" y="11" width="3" height="9" rx="1.5"></rect>
                        <rect fill="#000000" x="3" y="13" width="3" height="7" rx="1.5"></rect>
                    </g>
                </svg>
                <!--end::Svg Icon-->
            </span>
            <a href="#" class="text-info font-weight-bold font-size-h6">Total Mpesa Transactions: {{ $transactionsCount }}</a>
        </div>
    </div>
    <!--begin::Card-->
    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Transactions</h3>
            </div>
        </div>
        <div class="status-links">
          <a href="{{ route('admin.mpesa.index') }}">
              <span class="badge badge-success">View Completed Transactions</span>
          </a>
          <a href="{{ route('admin.mpesa.transactions.failed') }}">
              <span class="badge badge-danger">View Failed Transactions</span>
          </a>
      </div>
        <!--end::Button-->
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-bordered table-hover table-checkable mt-10" id="kt_datatable" style="margin-top: 13px !important">
                <thead>
                <tr>
                    {{-- <th>No</th> --}}
                    <th>Order Number</th>
                    <th>User Details</th>
                    {{--<th>Category</th>--}}
                    <th>Book</th>
                    {{-- <th>Channel</th> --}}
                    <th>Transaction ID</th>
                    <th>Amount Paid (KSH)</th>
                    <th>Payer PhoneNumber</th>
                    <th>Date Paid</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                </thead>
            </table>
            <!--end: Datatable-->
        </div>
    </div>
    <!--end::Card-->
    <div id="studentModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="post" id="student_form">
                    {{ csrf_field() }}
                    @csrf
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Edit Transaction</h4>
                    </div>
                    <div class="modal-body">
                        <span id="form_output"></span>
                        <div class="form-group">
                            <label>Transaction ID</label>
                            <input type="text" name="mpesaReceiptNumber" placeholder="Mpesa Receipt Number" id="mpesaReceiptNumber" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Amount</label>
                            <input type="text" name="amount" placeholder="Amount" id="amount" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Phone Number</label>
                            <input type="text" name="phone_number" placeholder="Phone Number" id="phone_number" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Status</label>
                            <select required class="form-control form-control-lg form-control-solid" id="transaction-status" name="status">
                                <option value="1">Completed</option>
                                <option value="0">Failed</option>
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="hidden" name="id" id="id" value="" />
                        <input type="hidden" name="button_action" id="button_action" value="insert" />
                        <input type="submit" name="submit" id="action" value="Add" class="btn btn-info" />

                        <div class="form-group">
                            <button type="button" class="btn btn-light btn-elevate mr-3" data-dismiss="modal">Cancel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        'use strict';
        var KTDatatablesDataSourceAjaxClient = function() {
            var initTable1 = function() {
                var table = $('#kt_datatable').DataTable({
                    dom: 'Bfrtip',
                    "processing": true,
                    "serverSide": true,
                    buttons: [{extend: 'copyHtml5'}, {
                        extend: 'excelHtml5',
                        exportOptions: {columns: ':visible'},
                    },
                        {
                            extend: 'pdfHtml5',
                            exportOptions: {columns: ':visible'},
                            orientation: 'landscape',
                            pageSize: 'TABLOID'
                        },
                        'colvis','pageLength'],
                    "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                    responsive: true,
                    ajax: {
                        url: '{!! route('admin.mpesa.data.failed') !!}',
                        data: function (d) {
                            d.region_id = $('select[name=region_id]').val();
                            d.raw_material_id = $('select[name=raw_material_id]').val();
                        }
                    },
                    columns: [
                        // {data: 'DT_RowIndex', name: 'DT_RowIndex', searchable: false, orderable: false},
                        {data: 'order_number', name: 'order_number'},
                        {data: 'user_details', name: 'user_details'},
                        // {data: 'category', name: 'category'},
                        {data: 'book_name', name: 'order_number'},
                        // {data: 'channel', name: 'channel'},
                        {data: 'mpesaReceiptNumber', name: 'mpesaReceiptNumber'},
                        {data: 'amount', name: 'amount'},
                        {data: 'phoneNumber', name: 'phoneNumber'},
                        {data: 'transactionDate', name: 'transactionDate'},
                        {data: 'status', name: 'status'},
                        {data: 'action', name: 'action'},
                    ],
                    columnDefs: [
                    ],
                });
                table.order([6, 'desc']).draw()
                $('#filter_form').on('submit', function(e) {
                    table.draw();
                    e.preventDefault();
                });
            };
            return {
                //main function to initiate the module
                init: function() {
                    initTable1();
                },
            };
        }();
        jQuery(document).ready(function() {
            KTDatatablesDataSourceAjaxClient.init();
        });

        $(document).on('click', '.edit-transaction', function(e){
            e.preventDefault()
            var id = $(this).attr("id");
            $('#form_output').html('');
            $.ajax({
                url:"{{route('admin.ajaxdata.fetchtransaction')}}",
                method:'get',
                data:{id:id},
                dataType:'json',
                success:function(data)
                {
                    console.log(data);
                    $('#mpesaReceiptNumber').val(data.mpesaReceiptNumber);
                    $('#transaction-status > option[value="'+data.status+'"]').attr('selected', true);
                    $('#phone_number').val(data.phone_number);
                    $('#amount').val(data.amount);
                    $('#id').val(id);
                    $('#studentModal').modal('show');
                    $('#action').val('Edit');
                    $('.modal-title').text('Edit Transaction');
                    $('#button_action').val('update');
                }
            })
        });

        $('#student_form').on('submit', function(event){
            event.preventDefault();
            var form_data = $(this).serialize();
            console.log(form_data)
            $.ajax({
                url:"{{ route('admin.ajaxdata.updatetransaction') }}",
                method:"POST",
                data:form_data,
                dataType:"json",
                success:function(data)
                {
                    if(data.error.length > 0)
                    {
                        var error_html = '';
                        for(var count = 0; count < data.error.length; count++)
                        {
                            error_html += '<div class="alert alert-danger">'+data.error[count]+'</div>';
                        }
                        $('#form_output').html(error_html);
                    }
                    else
                    {
                        $('#form_output').html(data.success);
                        $('#kt_datatable').DataTable().ajax.reload()
                        setTimeout(() => {
                            $('#studentModal').modal('hide');
                            $('#student_form')[0].reset();
                        }, 3000);
                    }
                }
            })
        });
    </script>
@endsection

resources/views/admin/transaction/iframe.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Make Payment</title>
</head>
<body>

{{--This will load the payment module from Pesapal, only if your details had no errors--}}
<iframe src="{{$iframe}}" width="100%" height="700px"  scrolling="no" frameBorder="0">
    <p>Browser unable to load iFrame</p>
</iframe>

</body>
</html>